dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - - chmod +x mvnw
script: mvn test -Dspring.profiles.active=mysql-travis
notifications:
  email: lucianolopez4000@hotmail.com


