language: node_js

node_js:
  - 11.6.0

sudo: required

env: DISPLAY=':99.0'

dist: trusty

addons:
  chrome: stable
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
install:
  - npm install
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
