language: java
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
script: "./mvnw clean install"
notifications:
  email: samm85299@gmail.com


